- name: Install Docker
  apt: name=docker.io

- name: Enable Docker
  service:
    name: docker
    enabled: yes

- name: Install apt-transport-https
  apt: name=apt-transport-https

- name: Install k8s packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - kubelet
    - kubeadm
    - kubectl

- name: Hold k8s packages
  dpkg_selections: name={{ item }} selection=hold
  with_items:
    - kubelet 
    - kubeadm
    - kubectl

- name: Initialize the cluster
  shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
  args:
    chdir: $HOME
    creates: cluster_initialized.txt
    
- name: create .kube directory
  file:
    path: $HOME/.kube
    state: directory

- name: copy /etc/kubernetes/admin.conf to .kube
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes

- name: install Pod network
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml >> pod_network_setup.txt
  args:
    chdir: $HOME
    creates: pod_network_setup.txt

- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command

- name: set join command
  set_fact: join_command={{ join_command.stdout }} 


